// road-app/src/components/ImageUpload.vue
<template>
  <div class="image-upload">
    <ion-label class="ion-text-wrap ion-margin-bottom">
      <h3>Photos du signalement</h3>
    </ion-label>

    <!-- Zone d'upload -->
    <div class="upload-zone" @click="selectImages">
      <ion-icon 
        :icon="cloudUploadOutline" 
        class="upload-icon"
        :class="{ 'uploading': uploading }"
      ></ion-icon>
      <p class="upload-text">
        {{ uploading ? 'Upload en cours...' : 'Cliquez pour ajouter des photos' }}
      </p>
      <p class="upload-subtitle">PNG, JPG jusqu'à 10MB</p>
    </div>

    <input
      ref="fileInput"
      type="file"
      accept="image/*"
      multiple
      @change="handleFileSelect"
      style="display: none"
    />

    <!-- Prévisualisation des images -->
    <div class="image-preview-grid" v-if="previewImages.length > 0">
      <div 
        v-for="(image, index) in previewImages" 
        :key="index"
        class="image-preview-item"
      >
        <img :src="image.url" :alt="`Photo ${index + 1}`" />
        <div class="image-overlay">
          <ion-button 
            fill="clear" 
            size="small" 
            @click="removeImage(index)"
            class="remove-button"
          >
            <ion-icon :icon="closeOutline"></ion-icon>
          </ion-button>
          <ion-button 
            fill="clear" 
            size="small" 
            @click="setMainImage(index)"
            class="main-button"
            :class="{ 'is-main': image.isMain }"
          >
            <ion-icon :icon="starOutline"></ion-icon>
          </ion-button>
        </div>
        <div class="main-badge" v-if="image.isMain">
          <ion-icon :icon="star"></ion-icon>
        </div>
      </div>
    </div>

    <!-- Progress bar -->
    <ion-progress-bar 
      v-if="uploading" 
      type="indeterminate" 
      class="upload-progress"
    ></ion-progress-bar>
  </div>
</template>

<script setup>
import { ref, defineEmits, defineProps } from 'vue';
import { 
  IonLabel, 
  IonIcon, 
  IonButton, 
  IonProgressBar,
  toastController
} from '@ionic/vue';
import { 
  cloudUploadOutline, 
  closeOutline, 
  starOutline, 
  star 
} from 'ionicons/icons';
import { uploadMultipleImages, createImageObject } from '../services/cloudinary';

const props = defineProps({
  initialImages: {
    type: Array,
    default: () => []
  },
  maxImages: {
    type: Number,
    default: 5
  }
});

const emit = defineEmits(['images-change']);

const fileInput = ref(null);
const uploading = ref(false);
const previewImages = ref([]);

// Initialiser avec les images existantes
if (props.initialImages.length > 0) {
  previewImages.value = props.initialImages.map((img, index) => 
    createImageObject(img, index === 0)
  );
}

const selectImages = () => {
  if (uploading.value) return;
  fileInput.value?.click();
};

const handleFileSelect = async (event) => {
  const files = Array.from(event.target.files);
  
  if (files.length === 0) return;
  if (previewImages.value.length + files.length > props.maxImages) {
    showToast(`Maximum ${props.maxImages} images autorisées`);
    return;
  }

  uploading.value = true;

  try {
    const uploadedUrls = await uploadMultipleImages(files);
    
    // Ajouter les nouvelles images à la prévisualisation
    const newImages = uploadedUrls.map((url, index) => {
      const isFirstImage = previewImages.value.length === 0 && index === 0;
      return createImageObject(url, isFirstImage);
    });

    previewImages.value = [...previewImages.value, ...newImages];
    emitImagesChange();
    
    showToast(`${files.length} image(s) uploadée(s) avec succès`);
    
  } catch (error) {
    console.error('Erreur upload:', error);
    showToast('Erreur lors de l\'upload des images');
  } finally {
    uploading.value = false;
    // Réinitialiser l'input
    event.target.value = '';
  }
};

const removeImage = (index) => {
  previewImages.value.splice(index, 1);
  
  // Si on supprime l'image principale, la première devient principale
  if (previewImages.value.length > 0 && !previewImages.value.some(img => img.isMain)) {
    previewImages.value[0].isMain = true;
  }
  
  emitImagesChange();
  showToast('Image supprimée');
};

const setMainImage = (index) => {
  // Toutes les images deviennent non principales
  previewImages.value.forEach(img => img.isMain = false);
  // L'image sélectionnée devient principale
  previewImages.value[index].isMain = true;
  
  emitImagesChange();
  showToast('Image principale définie');
};

const emitImagesChange = () => {
  const mainImage = previewImages.value.find(img => img.isMain);
  const otherImages = previewImages.value.filter(img => !img.isMain);
  
  emit('images-change', {
    imageUrl: mainImage?.url,
    images: otherImages.map(img => img.url)
  });
};

const showToast = async (message) => {
  const toast = await toastController.create({
    message,
    duration: 2000,
    position: 'bottom'
  });
  await toast.present();
};
</script>

<style scoped>
.image-upload {
  margin: 16px 0;
}

.upload-zone {
  border: 2px dashed #ccc;
  border-radius: 8px;
  padding: 32px 16px;
  text-align: center;
  cursor: pointer;
  transition: all 0.3s ease;
  background: #f9f9f9;
}

.upload-zone:hover {
  border-color: #3880ff;
  background: #f0f8ff;
}

.upload-icon {
  font-size: 48px;
  color: #ccc;
  margin-bottom: 8px;
  transition: color 0.3s ease;
}

.upload-icon.uploading {
  color: #3880ff;
  animation: pulse 1.5s infinite;
}

@keyframes pulse {
  0% { opacity: 1; }
  50% { opacity: 0.5; }
  100% { opacity: 1; }
}

.upload-text {
  margin: 8px 0 4px;
  font-weight: 600;
  color: #333;
}

.upload-subtitle {
  margin: 0;
  font-size: 12px;
  color: #666;
}

.image-preview-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(100px, 1fr));
  gap: 8px;
  margin-top: 16px;
}

.image-preview-item {
  position: relative;
  aspect-ratio: 1;
  border-radius: 8px;
  overflow: hidden;
  box-shadow: 0 2px 8px rgba(0,0,0,0.1);
}

.image-preview-item img {
  width: 100%;
  height: 100%;
  object-fit: cover;
}

.image-overlay {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(0,0,0,0.5);
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  padding: 4px;
  opacity: 0;
  transition: opacity 0.3s ease;
}

.image-preview-item:hover .image-overlay {
  opacity: 1;
}

.remove-button {
  --color: #ff4961;
}

.main-button {
  --color: #ffc107;
}

.main-button.is-main {
  --color: #ffc107;
}

.main-badge {
  position: absolute;
  top: 4px;
  right: 4px;
  background: #ffc107;
  color: #333;
  border-radius: 50%;
  width: 24px;
  height: 24px;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 12px;
}

.upload-progress {
  margin-top: 16px;
}
</style>

// frontend-visiteur/src/components/ImageUpload.tsx
import { useState } from 'react';
import { uploadImage } from '../lib/cloudinary';

interface ImageUploadProps {
  onImagesChange: (images: { imageUrl?: string; images?: string[] }) => void;
  initialImages?: { imageUrl?: string; images?: string[] };
  maxImages?: number;
}

export default function ImageUpload({ 
  onImagesChange, 
  initialImages, 
  maxImages = 5 
}: ImageUploadProps) {
  const [uploading, setUploading] = useState(false);
  const [previewImages, setPreviewImages] = useState<{
    imageUrl?: string;
    images: string[];
  }>({
    imageUrl: initialImages?.imageUrl,
    images: initialImages?.images || []
  });

  const handleFileSelect = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(event.target.files || []);
    
    if (files.length === 0) return;

    setUploading(true);

    try {
      const uploadPromises = files.map(file => uploadImage(file));
      const uploadedUrls = await Promise.all(uploadPromises);

      // Si c'est la première image, la mettre en imageUrl
      // Sinon, l'ajouter au tableau images
      let newImageUrl = previewImages.imageUrl;
      let newImages = [...previewImages.images];

      if (files.length === 1 && !previewImages.imageUrl) {
        newImageUrl = uploadedUrls[0];
      } else {
        newImages = [...newImages, ...uploadedUrls].slice(0, maxImages);
      }

      const updatedImages = {
        imageUrl: newImageUrl,
        images: newImages
      };

      setPreviewImages(updatedImages);
      onImagesChange(updatedImages);

    } catch (error) {
      console.error('Erreur lors de l\'upload:', error);
      alert('Erreur lors de l\'upload des images');
    } finally {
      setUploading(false);
    }
  };

  const removeImage = (index: number) => {
    const newImages = previewImages.images.filter((_, i) => i !== index);
    const updatedImages = {
      imageUrl: previewImages.imageUrl,
      images: newImages
    };
    setPreviewImages(updatedImages);
    onImagesChange(updatedImages);
  };

  const removeMainImage = () => {
    const updatedImages = {
      imageUrl: undefined,
      images: previewImages.images
    };
    setPreviewImages(updatedImages);
    onImagesChange(updatedImages);
  };

  return (
    <div className="space-y-4">
      <div className="mb-4">
        <label className="block text-sm font-medium text-gray-700 mb-2">
          Photos du signalement
        </label>
        <div className="flex items-center justify-center w-full">
          <label className="flex flex-col items-center justify-center w-full h-32 border-2 border-gray-300 border-dashed rounded-lg cursor-pointer bg-gray-50 hover:bg-gray-100">
            <div className="flex flex-col items-center justify-center pt-5 pb-6">
              {uploading ? (
                <div className="text-blue-600">
                  <svg className="animate-spin h-8 w-8" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                  </svg>
                  <p className="mt-2 text-sm text-gray-600">Upload en cours...</p>
                </div>
              ) : (
                <>
                  <svg className="w-8 h-8 mb-2 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12" />
                  </svg>
                  <p className="mb-2 text-sm text-gray-600">
                    <span className="font-semibold">Cliquez pour uploader</span> ou glissez-déposez
                  </p>
                  <p className="text-xs text-gray-500">
                    PNG, JPG, GIF jusqu'à 10MB
                  </p>
                </>
              )}
            </div>
            <input
              type="file"
              className="hidden"
              accept="image/*"
              multiple={true}
              onChange={handleFileSelect}
              disabled={uploading}
            />
          </label>
        </div>
      </div>

      {/* Image principale */}
      {previewImages.imageUrl && (
        <div className="mb-4">
          <h4 className="text-sm font-medium text-gray-700 mb-2">Image principale</h4>
          <div className="relative inline-block">
            <img
              src={previewImages.imageUrl}
              alt="Image principale"
              className="w-32 h-32 object-cover rounded-lg shadow-md"
            />
            <button
              type="button"
              onClick={removeMainImage}
              className="absolute -top-2 -right-2 bg-red-500 text-white rounded-full p-1 hover:bg-red-600"
            >
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
        </div>
      )}

      {/* Images multiples */}
      {previewImages.images.length > 0 && (
        <div>
          <h4 className="text-sm font-medium text-gray-700 mb-2">Autres photos</h4>
          <div className="grid grid-cols-3 gap-2">
            {previewImages.images.map((image, index) => (
              <div key={index} className="relative">
                <img
                  src={image}
                  alt={`Photo ${index + 1}`}
                  className="w-24 h-24 object-cover rounded-lg shadow-md"
                />
                <button
                  type="button"
                  onClick={() => removeImage(index)}
                  className="absolute -top-1 -right-1 bg-red-500 text-white rounded-full p-1 hover:bg-red-600"
                >
                  <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                  </svg>
                </button>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
